
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      console.setting.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassNamer: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher